spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/theiaDB
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: create
      show-sql: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG